/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacioneaqui;

/**
 *
 * @author Rodolfo
 */
public class TelaCadastroPessoa extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroPessoa
     */
    public TelaCadastroPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTelefoneCadastroPessoa = new javax.swing.JTextField();
        jPlacaCarroCadastroPessoa = new javax.swing.JTextField();
        jModeloCadastroPessoa = new javax.swing.JTextField();
        jCorCadastroPessoa = new javax.swing.JTextField();
        jNomeCadastroPessoa = new javax.swing.JTextField();
        jSobrenomeCadastroPessoa = new javax.swing.JTextField();
        jCpfCadastroPessoa = new javax.swing.JTextField();
        jRgCadastroPessoa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbVoltarCadastroPessoa = new javax.swing.JButton();
        jbConcluirCadastroPessoa = new javax.swing.JButton();
        jClienteCadastroPessoa = new javax.swing.JRadioButton();
        jFuncionarioCadastroPessoa = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Cadastro Pessoa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 100);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Nome:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 190, 60, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Tipo de Cadastro:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 130, 157, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Sobrenome:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 220, 110, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("CPF:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 250, 41, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("RG:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 280, 33, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Telefone:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(330, 190, 86, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Placa do Carro:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(330, 220, 138, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Modelo:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(330, 250, 72, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Cor:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(330, 280, 38, 22);
        getContentPane().add(jTelefoneCadastroPessoa);
        jTelefoneCadastroPessoa.setBounds(480, 180, 102, 30);
        getContentPane().add(jPlacaCarroCadastroPessoa);
        jPlacaCarroCadastroPessoa.setBounds(480, 210, 102, 30);
        getContentPane().add(jModeloCadastroPessoa);
        jModeloCadastroPessoa.setBounds(480, 240, 102, 30);
        getContentPane().add(jCorCadastroPessoa);
        jCorCadastroPessoa.setBounds(480, 270, 102, 30);

        jNomeCadastroPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeCadastroPessoaActionPerformed(evt);
            }
        });
        getContentPane().add(jNomeCadastroPessoa);
        jNomeCadastroPessoa.setBounds(130, 180, 130, 30);
        getContentPane().add(jSobrenomeCadastroPessoa);
        jSobrenomeCadastroPessoa.setBounds(130, 210, 130, 30);
        getContentPane().add(jCpfCadastroPessoa);
        jCpfCadastroPessoa.setBounds(130, 240, 130, 30);
        getContentPane().add(jRgCadastroPessoa);
        jRgCadastroPessoa.setBounds(130, 270, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Novo carro de cliente ?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 320, 190, 22);

        jbVoltarCadastroPessoa.setBackground(new java.awt.Color(255, 0, 51));
        jbVoltarCadastroPessoa.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jbVoltarCadastroPessoa.setText("Voltar");
        jbVoltarCadastroPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarCadastroPessoaActionPerformed(evt);
            }
        });
        getContentPane().add(jbVoltarCadastroPessoa);
        jbVoltarCadastroPessoa.setBounds(170, 380, 110, 50);

        jbConcluirCadastroPessoa.setBackground(new java.awt.Color(51, 255, 0));
        jbConcluirCadastroPessoa.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jbConcluirCadastroPessoa.setText("Concluir");
        jbConcluirCadastroPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConcluirCadastroPessoaActionPerformed(evt);
            }
        });
        getContentPane().add(jbConcluirCadastroPessoa);
        jbConcluirCadastroPessoa.setBounds(360, 380, 110, 50);

        jClienteCadastroPessoa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jClienteCadastroPessoa.setText("Cliente");
        getContentPane().add(jClienteCadastroPessoa);
        jClienteCadastroPessoa.setBounds(210, 130, 73, 29);

        jFuncionarioCadastroPessoa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jFuncionarioCadastroPessoa.setText("Funcionário");
        getContentPane().add(jFuncionarioCadastroPessoa);
        jFuncionarioCadastroPessoa.setBounds(310, 130, 110, 29);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbConcluirCadastroPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConcluirCadastroPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbConcluirCadastroPessoaActionPerformed

    private void jNomeCadastroPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeCadastroPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeCadastroPessoaActionPerformed

    private void jbVoltarCadastroPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarCadastroPessoaActionPerformed
        TelaCadastros telaCadastros = new TelaCadastros();
        telaCadastros.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jbVoltarCadastroPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jClienteCadastroPessoa;
    private javax.swing.JTextField jCorCadastroPessoa;
    private javax.swing.JTextField jCpfCadastroPessoa;
    private javax.swing.JRadioButton jFuncionarioCadastroPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jModeloCadastroPessoa;
    private javax.swing.JTextField jNomeCadastroPessoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPlacaCarroCadastroPessoa;
    private javax.swing.JTextField jRgCadastroPessoa;
    private javax.swing.JTextField jSobrenomeCadastroPessoa;
    private javax.swing.JTextField jTelefoneCadastroPessoa;
    private javax.swing.JButton jbConcluirCadastroPessoa;
    private javax.swing.JButton jbVoltarCadastroPessoa;
    // End of variables declaration//GEN-END:variables
}
